spring.application.name=WallterMasterING
spring.datasource.url=jdbc:postgresql://localhost:5434/walletmaster
spring.datasource.username=wallet_user
spring.datasource.password=wallet_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true